<?php


namespace app\admin\controller;



use think\Controller;
use think\Db;
Use think\Request;

class Stayhome extends Controller
{
    public $validate;
    public $code;

    //创建一个simpleXMLEmlement对象
    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->code = config('code');
        $this->validate = validate('Stayhome');
    }
    //执行任何方法之前都会执行这个方法
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        //
        $data = $this->request->get();
        if (isset($data['page']) && !empty($data['page'])) {
            $page = $data['page'];
        } else {
            $page = 1;
        }

        if (isset($data['limit']) && !empty($data['limit'])) {
            $limit = $data['limit'];
        } else {
            $limit = 10;
        }

        //处理搜索条件
        $where = [];
        if (isset($data['scity']) && !empty($data['scity'])) {
            $where['scity'] = $data['scity'];
        }
        if (isset($data['sname']) && !empty($data['sname'])) {
            $where['sname'] = ['like', '%' . $data['sname'] . '%'];
        }
        $result = Db::table('stayhome')->where($where)->paginate($limit, false, ['page=>$page']);
        //查询当前数据
        $stayhome = $result->items();
        //查询总数
        $total = $result->total();
        if ($total && $stayhome) {
            return json([
                'code' => 200,
                'msg' => '数据获取成功',
                'data' => $stayhome,
                'total' => $total,
            ]);
        } else {
            return json([
                'code' => 404,
                'msg' => '数据获取失败',
            ]);
        }
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
        return 'create';
    }

    /**
     * 保存新建的资源
     *
     * @param \think\Request $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
        $data = $this->request->post();

        //判断字段是否重复
        $sname = $data['sname'];
        $isExist = Db::table('stayhome')->where('sname', $sname)->count();
        if ($isExist) {
            return json([
                'code' => $this->code['fail'],
                'msg' => '请勿重复添加'
            ]);
        }
        $data['ctime'] = time();
        $result = Db::table('stayhome')->insert($data);
        if ($result) {
            return json([
                'code' => $this->code['success'],
                'msg' => '数据添加成功'
            ]);
        } else {
            return json([
                'code' => $this->code['fail'],
                'msg' => '数据添加失败'
            ]);
        }
    }

    /**
     * 显示指定的资源
     *
     * @param int $id
     * @return \think\Response
     */
    public function read($id)
    {
        $data = Db::table('stayhome')->where('sid',$id)->find();

        if($data){
            $data['sbanner1'] = explode(',' ,$data['sbanner']);
            return json([
                'code'=> $this->code['success'],
                'msg'=>'数据获取成功',
                'data'=> $data
            ]);
        }else{
            return json([
                'code'=> $this->code['success'],
                'msg'=>'暂无数据'
            ]);
        }

    }

    /**
     * 显示编辑资源表单页.
     *
     * @param int $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
        return 'edit';
    }

    /**
     * 保存更新的资源
     *
     * @param \think\Request $request
     * @param int $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
        return 'update';
    }

    /**
     * 删除指定资源
     *
     * @param int $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
        return 'delete';
    }

}